spring:
  application:
    name: gateway-echappeBelle
  cloud:
    gateway:
#      permet d'autoiser les requete options pour permettre les
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicles
          predicates:
            - Path=/vehicles/**
          uri: lb://ECHAPPEEBELLEVEHICLE

        - id: users
          predicates:
            - Path=/users/**
          uri: lb://USERS

        - id: bookings
          predicates:
            - Path=/bookings/**
          uri: lb://BOOKING


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.DispatcherHandler: TRACE
    reactor.netty: DEBUG

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka